const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    //admin
    // ADMIN_LOGIN_FAILDED: '': 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //Admin
    FETCH_GENDER_START: "FETCH_GENDER_START",
    FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAILDED: "FETCH_GENDER_FAILDED",

    FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAILDED: "FETCH_ROLE_FAILDED",

    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_FAILDED: 'SAVE_USER_FAILDED',

    FETCH_ALL_APPOINTMENT_TIME_SUCCESS: 'FETCH_ALL_APPOINTMENT_TIME_SUCCESS',
    FETCH_ALL_APPOINTMENT_TIME_FAILDED: 'FETCH_ALL_APPOINTMENT_TIME_FAILDED',

    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_FAILDED: 'FETCH_ALL_PRODUCT_FAILDED',

    FETCH_STATUS_SUCCESS: "FETCH_STATUS_SUCCESS",
    FETCH_STATUS_FAILDED: "FETCH_STATUS_FAILDED",

    FETCH_ALL_TEMP_SUCCESS: 'FETCH_ALL_TEMP_SUCCESS',
    FETCH_ALL_TEMP_FAILDED: 'FETCH_ALL_TEMP_FAILDED',

    FETCH_All_NEWS_SUCCESS: 'FETCH_All_NEWS_SUCCESS',
    FETCH_All_NEWS_FAILED: 'FETCH_All_NEWS_FAILED',
    SAVE_NEWS_SUCCESS: 'SAVE_NEWS_SUCCESS',
    SAVE_NEWS_FAILED: 'SAVE_NEWS_FAILED',
    EDIT_NEWS_SUCCESS: 'EDIT_NEWS_SUCCESS',
    EDIT_NEWS_FAILED: 'EDIT_NEWS_FAILED',
    DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS',
    DELETE_NEWS_FAILED: 'DELETE_NEWS_FAILED'

})

export default actionTypes;